---

- hosts: localhost
  vars:
    power_state: "start"
  roles:
    - { role: toggle_build_power_state, tags: toggle_build_power_state }

- hosts: build
  roles:
    - { role: deploy_portfolio, become: yes, tags: deploy_portfolio }

- hosts: localhost
  vars:
    power_state: "stop"
  roles:
    - { role: toggle_build_power_state, tags: toggle_build_power_state }
