---

- hosts: build
  roles:
    - { role: dependencies, become: yes, tags: dependencies }
    - { role: ssh_key, become: no, tags: ssh_key }
    - { role: node, become: yes, tags: node }
    - { role: angular, become: yes, tags: angular }
