---

aws_secret: "{{ lookup('aws_secret', 'prod/secret') }}"

square_access_token: "{{ aws_secret.square_access_token }}"
ssh_public_key: "{{ aws_secret.ssh_public_key }}"
ssh_private_key: "{{ aws_secret.ssh_private_key }}"

ssh_private_key_file: "{{ ansible_user_home }}/.ssh/id_rsa"
